"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .lambdadberror import LambdaDBError
from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .apierror import APIError
    from .badrequest_error import BadRequestError, BadRequestErrorData
    from .contract_errors import (
        BadGatewayError,
        BadGatewayErrorData,
        CatalogConflictError,
        CatalogConflictErrorData,
        GatewayTimeoutError,
        GatewayTimeoutErrorData,
        PayloadTooLargeError,
        PayloadTooLargeErrorData,
        ServiceUnavailableError,
        ServiceUnavailableErrorData,
    )
    from .internalservererror import InternalServerError, InternalServerErrorData
    from .no_response_error import NoResponseError
    from .resourcealreadyexists_error import (
        ResourceAlreadyExistsError,
        ResourceAlreadyExistsErrorData,
    )
    from .resourcenotfound_error import ResourceNotFoundError, ResourceNotFoundErrorData
    from .responsevalidationerror import ResponseValidationError
    from .toomanyrequests_error import TooManyRequestsError, TooManyRequestsErrorData
    from .unauthenticated_error import UnauthenticatedError, UnauthenticatedErrorData

__all__ = [
    "APIError",
    "BadRequestError",
    "BadRequestErrorData",
    "BadGatewayError",
    "BadGatewayErrorData",
    "CatalogConflictError",
    "CatalogConflictErrorData",
    "GatewayTimeoutError",
    "GatewayTimeoutErrorData",
    "InternalServerError",
    "InternalServerErrorData",
    "LambdaDBError",
    "NoResponseError",
    "PayloadTooLargeError",
    "PayloadTooLargeErrorData",
    "ResourceAlreadyExistsError",
    "ResourceAlreadyExistsErrorData",
    "ResourceNotFoundError",
    "ResourceNotFoundErrorData",
    "ResponseValidationError",
    "ServiceUnavailableError",
    "ServiceUnavailableErrorData",
    "TooManyRequestsError",
    "TooManyRequestsErrorData",
    "UnauthenticatedError",
    "UnauthenticatedErrorData",
]

_dynamic_imports: dict[str, str] = {
    "APIError": ".apierror",
    "BadRequestError": ".badrequest_error",
    "BadRequestErrorData": ".badrequest_error",
    "BadGatewayError": ".contract_errors",
    "BadGatewayErrorData": ".contract_errors",
    "CatalogConflictError": ".contract_errors",
    "CatalogConflictErrorData": ".contract_errors",
    "GatewayTimeoutError": ".contract_errors",
    "GatewayTimeoutErrorData": ".contract_errors",
    "InternalServerError": ".internalservererror",
    "InternalServerErrorData": ".internalservererror",
    "NoResponseError": ".no_response_error",
    "PayloadTooLargeError": ".contract_errors",
    "PayloadTooLargeErrorData": ".contract_errors",
    "ResourceAlreadyExistsError": ".resourcealreadyexists_error",
    "ResourceAlreadyExistsErrorData": ".resourcealreadyexists_error",
    "ResourceNotFoundError": ".resourcenotfound_error",
    "ResourceNotFoundErrorData": ".resourcenotfound_error",
    "ResponseValidationError": ".responsevalidationerror",
    "ServiceUnavailableError": ".contract_errors",
    "ServiceUnavailableErrorData": ".contract_errors",
    "TooManyRequestsError": ".toomanyrequests_error",
    "TooManyRequestsErrorData": ".toomanyrequests_error",
    "UnauthenticatedError": ".unauthenticated_error",
    "UnauthenticatedErrorData": ".unauthenticated_error",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
