"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .lambdadberror import LambdaDBError
from typing import Any, TYPE_CHECKING

from lambdadb.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .apierror import APIError
    from .badrequest_error import BadRequestError, BadRequestErrorData
    from .internalservererror import InternalServerError, InternalServerErrorData
    from .no_response_error import NoResponseError
    from .resourcealreadyexists_error import (
        ResourceAlreadyExistsError,
        ResourceAlreadyExistsErrorData,
    )
    from .resourcenotfound_error import ResourceNotFoundError, ResourceNotFoundErrorData
    from .responsevalidationerror import ResponseValidationError
    from .toomanyrequests_error import TooManyRequestsError, TooManyRequestsErrorData
    from .unauthenticated_error import UnauthenticatedError, UnauthenticatedErrorData

__all__ = [
    "APIError",
    "BadRequestError",
    "BadRequestErrorData",
    "InternalServerError",
    "InternalServerErrorData",
    "LambdaDBError",
    "NoResponseError",
    "ResourceAlreadyExistsError",
    "ResourceAlreadyExistsErrorData",
    "ResourceNotFoundError",
    "ResourceNotFoundErrorData",
    "ResponseValidationError",
    "TooManyRequestsError",
    "TooManyRequestsErrorData",
    "UnauthenticatedError",
    "UnauthenticatedErrorData",
]

_dynamic_imports: dict[str, str] = {
    "APIError": ".apierror",
    "BadRequestError": ".badrequest_error",
    "BadRequestErrorData": ".badrequest_error",
    "InternalServerError": ".internalservererror",
    "InternalServerErrorData": ".internalservererror",
    "NoResponseError": ".no_response_error",
    "ResourceAlreadyExistsError": ".resourcealreadyexists_error",
    "ResourceAlreadyExistsErrorData": ".resourcealreadyexists_error",
    "ResourceNotFoundError": ".resourcenotfound_error",
    "ResourceNotFoundErrorData": ".resourcenotfound_error",
    "ResponseValidationError": ".responsevalidationerror",
    "TooManyRequestsError": ".toomanyrequests_error",
    "TooManyRequestsErrorData": ".toomanyrequests_error",
    "UnauthenticatedError": ".unauthenticated_error",
    "UnauthenticatedErrorData": ".unauthenticated_error",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
