"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from lambdadb.errors import LambdaDBError
from lambdadb.types import BaseModel
from typing import Optional


class BadRequestErrorData(BaseModel):
    message: Optional[str] = None


@dataclass(unsafe_hash=True)
class BadRequestError(LambdaDBError):
    data: BadRequestErrorData = field(hash=False)

    def __init__(
        self,
        data: BadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
