"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from lambdadb.types import BaseModel
from .versioning import RefName
from lambdadb.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import ConfigDict
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BulkUpsertDocsRequestBodyTypedDict(TypedDict):
    object_key: str
    r"""Object key uploaded based on bulk upsert info."""
    type: NotRequired[str]
    branch: NotRequired[str]


class BulkUpsertDocsRequestBody(BaseModel):
    model_config = ConfigDict(extra="forbid")

    object_key: Annotated[str, pydantic.Field(alias="objectKey")]
    r"""Object key uploaded based on bulk upsert info."""
    type: str = "application/json"
    r"""Sent explicitly on upload completion; callers should not rely on a server default."""
    branch: Optional[RefName] = None


class BulkUpsertDocsRequestTypedDict(TypedDict):
    collection_name: str
    r"""Collection name."""
    request_body: BulkUpsertDocsRequestBodyTypedDict


class BulkUpsertDocsRequest(BaseModel):
    collection_name: Annotated[
        str,
        pydantic.Field(alias="collectionName"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Collection name."""

    request_body: Annotated[
        BulkUpsertDocsRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
