"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime, timezone
from .indexconfigs_union import IndexConfigsUnion, IndexConfigsUnionTypedDict
from .partitionconfig import PartitionConfig, PartitionConfigTypedDict
from lambdadb.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Dict, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CollectionResponseTypedDict(TypedDict):
    project_name: str
    r"""Project name."""
    collection_name: str
    r"""Collection name."""
    index_configs: Dict[str, IndexConfigsUnionTypedDict]
    num_partitions: int
    r"""Total number of partitions including the default partition."""
    num_docs: int
    r"""Total number of documents."""
    description: str
    tags: Dict[str, str]
    default_branch_name: Literal["main"]
    snapshot_retention_in_days: int
    created_at: int
    r"""Collection creation time in milliseconds since the Unix epoch."""
    updated_at: int
    r"""Collection last update time in milliseconds since the Unix epoch."""
    data_updated_at: NotRequired[int]
    r"""Collection data last update time in milliseconds since the Unix epoch."""
    partition_config: NotRequired[PartitionConfigTypedDict]


class CollectionResponse(BaseModel):
    project_name: Annotated[str, pydantic.Field(alias="projectName")]
    r"""Project name."""

    collection_name: Annotated[str, pydantic.Field(alias="collectionName")]
    r"""Collection name."""

    index_configs: Annotated[
        Dict[str, IndexConfigsUnion], pydantic.Field(alias="indexConfigs")
    ]

    num_partitions: Annotated[int, pydantic.Field(alias="numPartitions")]
    r"""Total number of partitions including the default partition."""

    num_docs: Annotated[int, pydantic.Field(alias="numDocs")]
    r"""Total number of documents."""

    description: str

    tags: Dict[str, str]

    default_branch_name: Annotated[
        Literal["main"], pydantic.Field(alias="defaultBranchName")
    ]

    snapshot_retention_in_days: Annotated[
        int, pydantic.Field(alias="snapshotRetentionInDays", ge=1, le=31)
    ]

    created_at: Annotated[int, pydantic.Field(alias="createdAt")]
    r"""Collection creation time in milliseconds since the Unix epoch."""

    updated_at: Annotated[int, pydantic.Field(alias="updatedAt")]
    r"""Collection last update time in milliseconds since the Unix epoch."""

    data_updated_at: Annotated[Optional[int], pydantic.Field(alias="dataUpdatedAt")] = None
    r"""Collection data last update time in milliseconds since the Unix epoch."""

    @property
    def created_at_dt(self) -> datetime:
        """Collection creation time as a timezone-aware UTC datetime."""
        return datetime.fromtimestamp(self.created_at / 1000, tz=timezone.utc)

    @property
    def updated_at_dt(self) -> datetime:
        """Collection last update time as a timezone-aware UTC datetime."""
        return datetime.fromtimestamp(self.updated_at / 1000, tz=timezone.utc)

    @property
    def data_updated_at_dt(self) -> Optional[datetime]:
        """Collection data last update time as a timezone-aware UTC datetime."""
        if self.data_updated_at is None:
            return None
        return datetime.fromtimestamp(self.data_updated_at / 1000, tz=timezone.utc)

    partition_config: Annotated[
        Optional[PartitionConfig], pydantic.Field(alias="partitionConfig")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "partitionConfig",
                "dataUpdatedAt",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = self._get_serialized_value(serialized, n, f.alias)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
