"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from lambdadb.types import BaseModel, UNSET_SENTINEL
from .versioning import RefName
from lambdadb.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetBulkUpsertDocsRequestTypedDict(TypedDict):
    collection_name: str
    r"""Collection name."""
    branch: NotRequired[str]


class GetBulkUpsertDocsRequest(BaseModel):
    collection_name: Annotated[
        str,
        pydantic.Field(alias="collectionName"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Collection name."""

    branch: Annotated[
        Optional[RefName],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None


class GetBulkUpsertDocsType(str, Enum):
    r"""Content type that must be specified when uploading documents."""

    APPLICATION_JSON = "application/json"


class HTTPMethod(str, Enum):
    r"""HTTP method that must be specified when uploading documents."""

    PUT = "PUT"


class GetBulkUpsertDocsResponseTypedDict(TypedDict):
    r"""Required info to upload documents."""

    url: str
    r"""Presigned URL."""
    object_key: str
    r"""Object key that must be specified when uploading documents."""
    type: GetBulkUpsertDocsType
    r"""Content type that must be specified when uploading documents."""
    http_method: HTTPMethod
    r"""HTTP method that must be specified when uploading documents."""
    size_limit_bytes: int
    r"""Object size limit in bytes."""
    headers: Dict[str, str]


class GetBulkUpsertDocsResponse(BaseModel):
    r"""Required info to upload documents."""

    url: str
    r"""Presigned URL."""

    object_key: Annotated[str, pydantic.Field(alias="objectKey")]
    r"""Object key that must be specified when uploading documents."""

    type: GetBulkUpsertDocsType
    r"""Content type that must be specified when uploading documents."""

    http_method: Annotated[HTTPMethod, pydantic.Field(alias="httpMethod")]
    r"""HTTP method that must be specified when uploading documents."""

    size_limit_bytes: Annotated[
        int, pydantic.Field(alias="sizeLimitBytes")
    ]
    r"""Object size limit in bytes."""

    headers: Dict[str, str]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set()
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = self._get_serialized_value(serialized, n, f.alias)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
