"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import warnings
from .fieldsselector_union import FieldsSelectorUnion, FieldsSelectorUnionTypedDict
from .partitionfilter import PartitionFilter, PartitionFilterTypedDict
from lambdadb.types import BaseModel, UNSET_SENTINEL
from lambdadb.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListDocsRequestTypedDict(TypedDict):
    collection_name: str
    r"""Collection name."""
    size: NotRequired[int]
    r"""Max number of documents to return at once."""
    page_token: NotRequired[str]
    r"""Next page token."""
    include_vectors: NotRequired[bool]
    r"""Set to true to include vector values in the response. Defaults to false."""


class ListDocsRequest(BaseModel):
    collection_name: Annotated[
        str,
        pydantic.Field(alias="collectionName"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Collection name."""

    size: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Max number of documents to return at once."""

    page_token: Annotated[
        Optional[str],
        pydantic.Field(alias="pageToken"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Next page token."""

    include_vectors: Annotated[
        Optional[bool],
        pydantic.Field(alias="includeVectors"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = False
    r"""Set to true to include vector values in the response. Defaults to false."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["size", "pageToken", "includeVectors"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = self._get_serialized_value(serialized, n, f.alias)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListDocsExtendedRequestBodyTypedDict(TypedDict):
    size: NotRequired[int]
    r"""Max number of documents to return at once."""
    page_token: NotRequired[str]
    r"""Next page token."""
    filter_: NotRequired[Dict[str, Any]]
    r"""Filter applied before pagination."""
    partition_filter: NotRequired[PartitionFilterTypedDict]
    fields: NotRequired[FieldsSelectorUnionTypedDict]
    r"""An object to specify a list of field names to include and/or exclude in the result."""
    include_vectors: NotRequired[bool]
    r"""Set to true to include vector values in the response. Defaults to false."""


class ListDocsExtendedRequestBody(BaseModel):
    size: Optional[int] = None
    r"""Max number of documents to return at once."""

    page_token: Annotated[Optional[str], pydantic.Field(alias="pageToken")] = None
    r"""Next page token."""

    filter_: Annotated[Optional[Dict[str, Any]], pydantic.Field(alias="filter")] = None
    r"""Filter applied before pagination."""

    partition_filter: Annotated[
        Optional[PartitionFilter], pydantic.Field(alias="partitionFilter")
    ] = None

    fields: Optional[FieldsSelectorUnion] = None
    r"""An object to specify a list of field names to include and/or exclude in the result."""

    include_vectors: Annotated[
        Optional[bool], pydantic.Field(alias="includeVectors")
    ] = False
    r"""Set to true to include vector values in the response. Defaults to false."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["size", "pageToken", "filter", "partitionFilter", "fields", "includeVectors"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = self._get_serialized_value(serialized, n, f.alias)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListDocsExtendedRequestTypedDict(TypedDict):
    collection_name: str
    r"""Collection name."""
    request_body: ListDocsExtendedRequestBodyTypedDict


class ListDocsExtendedRequest(BaseModel):
    collection_name: Annotated[
        str,
        pydantic.Field(alias="collectionName"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Collection name."""

    request_body: Annotated[
        ListDocsExtendedRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class ListDocsResponseTypedDict(TypedDict):
    r"""Documents list."""

    total: int
    results: List[Dict[str, Any]]
    r"""List of result items (documents or items with 'doc' key)."""
    next_page_token: NotRequired[str]
    is_docs_inline: bool
    r"""Whether the list of documents is included."""
    docs_url: NotRequired[str]
    r"""Download URL for the list of documents."""


class ListDocsResponse(BaseModel):
    r"""Documents list."""

    total: int

    results: Annotated[
        List[Dict[str, Any]],
        pydantic.Field(alias="docs"),
    ]
    r"""List of result items (documents or items with 'doc' key)."""

    next_page_token: Annotated[Optional[str], pydantic.Field(alias="nextPageToken")] = (
        None
    )

    is_docs_inline: Annotated[bool, pydantic.Field(alias="isDocsInline")]
    r"""Whether the list of documents is included."""

    docs_url: Annotated[Optional[str], pydantic.Field(alias="docsUrl")] = None
    r"""Download URL for the list of documents."""

    @property
    def docs(self) -> List[Dict[str, Any]]:
        """Deprecated: use .results instead. List of result items."""
        warnings.warn(
            "ListDocsResponse.docs is deprecated; use .results instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        return self.results

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["nextPageToken", "docsUrl"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = self._get_serialized_value(serialized, n, f.alias)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
