"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .fieldsselector_union import FieldsSelectorUnion, FieldsSelectorUnionTypedDict
from .partitionfilter import PartitionFilter, PartitionFilterTypedDict
from .versioning import Ref, RefKind
from .reranking import RerankConfig, RerankConfigTypedDict, RerankResponse, RerankResponseTypedDict
from .facets import FacetRequest, FacetRequestTypedDict, FacetResult, FacetResultTypedDict
from lambdadb.types import BaseModel, UNSET_SENTINEL
from lambdadb.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import ConfigDict
from pydantic import model_serializer, model_validator
import warnings
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class QueryCollectionRequestBodyTypedDict(TypedDict):
    query: NotRequired[Dict[str, Any]]
    r"""Query object."""
    rerank: NotRequired[Optional[RerankConfigTypedDict]]
    facets: NotRequired[Dict[str, FacetRequestTypedDict]]
    size: NotRequired[int]
    r"""Number of documents to return. Note that the maximum number of documents is 100."""
    consistent_read: NotRequired[bool]
    r"""Overlay eligible pending writes on a directly selected branch. Tags and aliases reject true, and pending bulk imports are excluded."""
    include_vectors: NotRequired[bool]
    r"""If your application need to include vector values in the response, set includeVectors to true."""
    sort: NotRequired[List[Dict[str, Any]]]
    r"""List of field name, sort direction pairs."""
    fields: NotRequired[FieldsSelectorUnionTypedDict]
    r"""An object to specify a list of field names to include and/or exclude in the result."""
    partition_filter: NotRequired[PartitionFilterTypedDict]
    ref: NotRequired[dict]


class QueryCollectionRequestBody(BaseModel):
    model_config = ConfigDict(extra="forbid")

    query: Optional[Dict[str, Any]] = None
    r"""Query object."""

    rerank: Optional[RerankConfig] = None
    facets: Optional[Dict[str, FacetRequest]] = None
    size: Optional[int] = None
    r"""Number of documents to return. Note that the maximum number of documents is 100."""

    consistent_read: Annotated[
        Optional[bool], pydantic.Field(alias="consistentRead")
    ] = False
    r"""Overlay eligible pending writes on a directly selected branch. Tags and aliases reject true, and pending bulk imports are excluded."""

    include_vectors: Annotated[
        Optional[bool], pydantic.Field(alias="includeVectors")
    ] = False
    r"""If your application need to include vector values in the response, set includeVectors to true."""

    sort: Optional[List[Dict[str, Any]]] = None
    r"""List of field name, sort direction pairs."""

    fields: Optional[FieldsSelectorUnion] = None
    r"""An object to specify a list of field names to include and/or exclude in the result."""

    partition_filter: Annotated[
        Optional[PartitionFilter], pydantic.Field(alias="partitionFilter")
    ] = None

    ref: Optional[Ref] = None

    @model_validator(mode="after")
    def validate_consistent_read_ref(self) -> "QueryCollectionRequestBody":
        if (
            self.consistent_read
            and self.ref is not None
            and self.ref.kind is not RefKind.BRANCH
        ):
            raise ValueError("consistent_read=True requires a direct branch ref")
        return self

    @model_validator(mode="after")
    def validate_rerank_context(self) -> "QueryCollectionRequestBody":
        if self.rerank is not None:
            size = 10 if self.size is None else self.size
            candidate_size = self.rerank.candidate_size
            if not 1 <= size <= 100 or (candidate_size is not None and candidate_size < size):
                raise ValueError("rerank requires 1 <= size <= candidate_size <= 100")
            if self.sort is not None:
                raise ValueError("rerank cannot be combined with sort")
            if not self.query:
                raise ValueError("rerank requires a scoring retrieval query")
            # The server validates the opaque query DSL and collection-dependent fields.
        return self

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "size",
                "query",
                "facets",
                "rerank",
                "consistentRead",
                "includeVectors",
                "sort",
                "fields",
                "partitionFilter",
                "ref",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = self._get_serialized_value(serialized, n, f.alias)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class QueryCollectionRequestTypedDict(TypedDict):
    collection_name: str
    r"""Collection name."""
    request_body: QueryCollectionRequestBodyTypedDict


class QueryCollectionRequest(BaseModel):
    collection_name: Annotated[
        str,
        pydantic.Field(alias="collectionName"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Collection name."""

    request_body: Annotated[
        QueryCollectionRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class QueryCollectionDocTypedDict(TypedDict):
    collection: str
    r"""Collection name."""
    doc: Dict[str, Any]
    retrieval_score: NotRequired[float]
    score: NotRequired[float]
    r"""Final ordering score: an evaluation score in [0, 1] on applied reranking, otherwise the retrieval/fusion score. Not a relevance probability."""


class QueryCollectionDoc(BaseModel):
    collection: str
    r"""Collection name."""

    doc: Dict[str, Any]

    retrieval_score: Annotated[Optional[float], pydantic.Field(alias="retrievalScore")] = None
    r"""Original retrieval/fusion score, present only when reranking is applied; outside the document body."""

    score: Optional[float] = None
    r"""Final ordering score: an evaluation score in [0, 1] on applied reranking, otherwise the retrieval/fusion score. Not a relevance probability."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["score", "retrievalScore"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = self._get_serialized_value(serialized, n, f.alias)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class QueryCollectionResponseTypedDict(TypedDict):
    r"""Documents selected by query."""

    rerank: NotRequired[RerankResponseTypedDict]
    facets: NotRequired[Dict[str, FacetResultTypedDict]]
    took: int
    r"""Elapsed time in milliseconds."""
    total: int
    r"""Total number of documents returned."""
    results: List[QueryCollectionDocTypedDict]
    r"""List of result items (each has .doc, .score, etc.). Use .documents for document bodies only."""
    is_docs_inline: bool
    r"""Whether the list of documents is included."""
    max_score: NotRequired[float]
    r"""Maximum final returned score. Omitted for empty results; numeric zero is preserved."""
    docs_url: NotRequired[str]
    r"""Optional download URL for the list of documents."""


class QueryCollectionResponse(BaseModel):
    r"""Documents selected by query."""

    rerank: Optional[RerankResponse] = None
    facets: Optional[Dict[str, FacetResult]] = None
    took: int
    r"""Elapsed time in milliseconds."""

    total: int
    r"""Total number of documents returned."""

    results: Annotated[
        List[QueryCollectionDoc],
        pydantic.Field(alias="docs"),
    ]
    r"""List of result items (each has .doc, .score, etc.). Use .documents for document bodies only."""

    is_docs_inline: Annotated[bool, pydantic.Field(alias="isDocsInline")]
    r"""Whether the list of documents is included."""

    max_score: Annotated[Optional[float], pydantic.Field(alias="maxScore")] = None
    r"""Maximum final returned score. Omitted for empty results; numeric zero is preserved."""

    docs_url: Annotated[Optional[str], pydantic.Field(alias="docsUrl")] = None
    r"""Optional download URL for the list of documents."""

    @property
    def documents(self) -> List[Dict[str, Any]]:
        """Convenience: list of document bodies only. Use .results when you need .score or .collection."""
        return [d.doc for d in self.results]

    @property
    def docs(self) -> List[QueryCollectionDoc]:
        """Deprecated: use .results instead. List of result items (each has .doc, .score, etc.)."""
        warnings.warn(
            "QueryCollectionResponse.docs is deprecated; use .results instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        return self.results

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["maxScore", "docsUrl", "facets", "rerank"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = self._get_serialized_value(serialized, n, f.alias)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
