"""Generated by scripts/generate_reranking.py; edit the scoped schema instead."""

from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict
from pydantic import ConfigDict, Field, StrictStr, field_validator, model_serializer
from lambdadb.types import BaseModel


class RerankConfigTypedDict(TypedDict):
    provider: Literal['typesafe']
    model: Literal['jev-1.13.0']
    query_text: str
    fields: List[str]
    candidate_size: NotRequired[Optional[int]]
    on_failure: NotRequired[Optional[Literal['error', 'returnOriginal']]]
    criteria: NotRequired[Optional[List[str]]]


class RerankConfig(BaseModel):
    """Managed reranking request."""
    model_config = ConfigDict(extra="forbid")

    provider: Literal['typesafe']
    """Server-managed reranking provider. No customer provider API key is required."""

    model: Literal['jev-1.13.0']
    """Explicit managed reranking model."""

    query_text: StrictStr = Field(alias="queryText")
    """Nonblank query text, at most 8 KiB UTF-8; required even for raw-vector retrieval."""

    fields: List[StrictStr] = Field(min_length=1, max_length=8)
    """Ordered unique stored scalar text paths (text or keyword). The server validates collection paths and candidate values."""

    candidate_size: Optional[int] = Field(default=None, alias="candidateSize", strict=True, ge=1, le=100)
    """Merged rerank candidate cap; defaults to max(50, size). Must be at least size; does not change knn.k."""

    on_failure: Optional[Literal['error', 'returnOriginal']] = Field(default=None, alias="onFailure")
    """Defaults to error. returnOriginal applies only to whole-stage provider failures, not input, quota, admission, retrieval or authorization errors."""

    criteria: Optional[List[StrictStr]] = Field(default=None, min_length=2, max_length=10)
    """Distinct nonblank descriptions ordered lowest to highest relevance. Omitted/null uses default criteria; at most 2 KiB each and 8 KiB total UTF-8."""

    @field_validator("query_text")
    @classmethod
    def validate_query_text(cls, value: str) -> str:
        if not value.strip() or len(value.encode("utf-8")) > 8192:
            raise ValueError("query_text must be nonblank and at most 8 KiB UTF-8")
        return value

    @field_validator("fields")
    @classmethod
    def validate_fields(cls, value: List[str]) -> List[str]:
        if len(set(value)) != len(value) or any(
            any(not part.strip() for part in path.split(".")) for path in value
        ):
            raise ValueError("fields must contain unique nonblank scalar text paths")
        return value

    @field_validator("criteria")
    @classmethod
    def validate_criteria(cls, value: Optional[List[str]]) -> Optional[List[str]]:
        if value is not None:
            sizes = [len(item.encode("utf-8")) for item in value]
            if (len(set(value)) != len(value) or any(not item.strip() for item in value)
                    or max(sizes) > 2048 or sum(sizes) > 8192):
                raise ValueError("criteria must be distinct and nonblank, at most 2 KiB each and 8 KiB total UTF-8")
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        for name, field in type(self).model_fields.items():
            if name not in ['candidate_size', 'on_failure', 'criteria']:
                continue
            key = field.alias if field.alias in serialized else name
            if serialized.get(key) is None:
                serialized.pop(key, None)
        return serialized


class RerankResponseTypedDict(TypedDict):
    status: Literal['applied', 'skipped', 'fallback']
    provider: str
    model: str
    resolved_model: NotRequired[Optional[str]]
    candidate_count: int
    scored_count: int
    took: int
    criteria_version: NotRequired[Optional[Literal['default-relevance-v1', 'custom']]]
    reason: NotRequired[Optional[str]]


class RerankResponse(BaseModel):
    """Managed reranking metadata."""
    status: Literal['applied', 'skipped', 'fallback']
    """Check status before interpreting scores: fallback keeps search scores."""

    provider: StrictStr
    """Requested provider."""

    model: StrictStr
    """Requested model."""

    resolved_model: Optional[StrictStr] = Field(default=None, alias="resolvedModel")
    """Resolved model when reported by the provider."""

    candidate_count: int = Field(alias="candidateCount")
    """Actual unique candidates in the logical stage; not a guaranteed count or billing unit."""

    scored_count: int = Field(alias="scoredCount")
    """Complete accepted scores; equals candidateCount on applied, zero on skipped/fallback."""

    took: int
    """Rerank stage duration in milliseconds, excluding candidate hydration."""

    criteria_version: Optional[Literal['default-relevance-v1', 'custom']] = Field(default=None, alias="criteriaVersion")
    """Only on applied results when reported. custom identifies caller-supplied criteria, not a content hash or unique version."""

    reason: Optional[StrictStr] = Field(default=None)
    """Skipped/fallback reason: noCandidates, timeout, rateLimit, unavailable, invalidResponse or credentials."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        for name, field in type(self).model_fields.items():
            if name not in ['resolved_model', 'criteria_version', 'reason']:
                continue
            key = field.alias if field.alias in serialized else name
            if serialized.get(key) is None:
                serialized.pop(key, None)
        return serialized
