workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    lambdadb-OAS:
        inputs:
            - location: https://raw.githubusercontent.com/lambdadb/docs/main/reference/api/openapi.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/lambdadb-ayw/lambdadb-python/lambdadb-oas
targets:
    lambdadb:
        target: python
        source: lambdadb-OAS
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/lambdadb-ayw/lambdadb-python/lambdadb-oas-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
