"""Generate scoped reranking models and references from the pinned contract."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def python_name(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def field_type(prop: dict, *, runtime: bool = False) -> str:
    if "enum" in prop:
        result = "Literal[" + ", ".join(repr(value) for value in prop["enum"]) + "]"
    elif prop["type"] == "array":
        result = "List[StrictStr]" if runtime else "List[str]"
    elif prop["type"] == "integer":
        result = "int"
    else:
        result = "StrictStr" if runtime else "str"
    return f"Optional[{result}]" if prop.get("nullable") else result


def generated_files() -> dict[Path, str]:
    contract = json.loads((ROOT / "schemas/native-reranking.json").read_text())
    output = '''"""Generated by scripts/generate_reranking.py; edit the scoped schema instead."""

from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict
from pydantic import ConfigDict, Field, StrictStr, field_validator, model_serializer
from lambdadb.types import BaseModel
'''
    files = {}
    for name, schema in contract["schemas"].items():
        required = schema["required"]
        props = schema["properties"]
        output += f"\n\nclass {name}TypedDict(TypedDict):\n"
        for wire_name, prop in props.items():
            typ = field_type(prop)
            if wire_name not in required:
                typ = f"NotRequired[{typ}]"
            output += f"    {python_name(wire_name)}: {typ}\n"
        output += f'\n\nclass {name}(BaseModel):\n    """Native reranking {"request" if name == "RerankConfig" else "metadata"}."""\n'
        if name == "RerankConfig":
            output += '    model_config = ConfigDict(extra="forbid")\n\n'
        for wire_name, prop in props.items():
            field = python_name(wire_name)
            args = [] if wire_name in required else ["default=None"]
            if field != wire_name:
                args.append(f'alias="{wire_name}"')
            if name == "RerankConfig":
                if prop["type"] == "integer":
                    args.extend(["strict=True", f'ge={prop["minimum"]}', f'le={prop["maximum"]}'])
                if prop["type"] == "array":
                    args.extend([f'min_length={prop["minItems"]}', f'max_length={prop["maxItems"]}'])
            value = f"Field({', '.join(args)})" if args else "None"
            suffix = f" = {value}" if args or wire_name not in required else ""
            output += f"    {field}: {field_type(prop, runtime=True)}{suffix}\n"
            output += f'    """{prop["description"]}"""\n\n'
        if name == "RerankConfig":
            output += f'''    @field_validator("query_text")
    @classmethod
    def validate_query_text(cls, value: str) -> str:
        if not value.strip() or len(value.encode("utf-8")) > {props['queryText']['x-maxUtf8Bytes']}:
            raise ValueError("query_text must be nonblank and at most 8 KiB UTF-8")
        return value

    @field_validator("fields")
    @classmethod
    def validate_fields(cls, value: List[str]) -> List[str]:
        if len(set(value)) != len(value) or any(
            any(not part.strip() for part in path.split(".")) for path in value
        ):
            raise ValueError("fields must contain unique nonblank scalar text paths")
        return value

    @field_validator("criteria")
    @classmethod
    def validate_criteria(cls, value: Optional[List[str]]) -> Optional[List[str]]:
        if value is not None:
            sizes = [len(item.encode("utf-8")) for item in value]
            if (len(set(value)) != len(value) or any(not item.strip() for item in value)
                    or max(sizes) > {props['criteria']['items']['x-maxUtf8Bytes']} or sum(sizes) > {props['criteria']['x-maxUtf8Bytes']}):
                raise ValueError("criteria must be distinct and nonblank, at most 2 KiB each and 8 KiB total UTF-8")
        return value

'''
        optional = [python_name(key) for key in props if key not in required]
        output += f'''    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        for name, field in type(self).model_fields.items():
            if name not in {optional!r}:
                continue
            key = field.alias if field.alias in serialized else name
            if serialized.get(key) is None:
                serialized.pop(key, None)
        return serialized
'''
        doc = f"# {name}\n\nGenerated from the [pinned contract](../../schemas/native-reranking.json).\n\n"
        doc += "| Field | Type | Required | Description |\n| --- | --- | --- | --- |\n"
        for key, prop in props.items():
            doc += f"| `{python_name(key)}` | `{field_type(prop)}` | {'Yes' if key in required else 'No'} | {prop['description']} |\n"
        doc += "\nSee [native reranking](../native-reranking.md) for examples and server validation.\n"
        files[ROOT / f"docs/models/{name.lower()}.md"] = doc
    files[ROOT / "src/lambdadb/models/reranking.py"] = output
    return files


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in generated_files().items():
        if not path.exists() or path.read_text() != content:
            stale.append(str(path.relative_to(ROOT)))
            if not args.check:
                path.write_text(content)
    if args.check and stale:
        parser.exit(1, "Stale reranking outputs: " + ", ".join(stale) + "\n")


if __name__ == "__main__":
    main()
